name: Mirror GHCR image to ECR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR (skip if image is public)
        if: ${{ secrets.GHCR_PAT != '' }}
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Pull from GHCR
        env:
          # ⬇️ Replace this with your actual GHCR image name
          GHCR_IMAGE: ghcr.io/juhi0589/hello-word-juhiirohila:latest
        run: |
          docker pull $GHCR_IMAGE

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag & push to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker tag $GHCR_IMAGE $ECR_REGISTRY/$ECR_REPOSITORY:prod
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:prod

      - name: Output image URI
        run: echo "Pushed: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:prod"
